FROM ubuntu:22.04 AS block-dev
ENV DEBIAN_FRONTEND noninteractive

RUN \
    apt-get update && \
    apt-get -y dist-upgrade && \
    apt-get install -y \
    software-properties-common \
    wget \
    make \
    g++ \
    cmake \
    zlib1g \
    zlib1g-dev \
    libsnappy-dev \
    libzstd-dev \
    libbz2-dev \
    liblz4-dev \
    libgflags-dev \
    liburing-dev \
    libssl-dev \
    libgflags-dev \
    libreadline-dev \
    git \
    vim \
    openssh-client \
    openssh-server \
    openssh-sftp-server \
    python3 \
    python3-pip \
    net-tools \
    iputils-ping \
    iproute2 \
    rsync \
    gdb \
    mysql-client \
    mysql-server

RUN pip3 install \
    paramiko

RUN rm -rf /root/block-db
COPY . /root/block-db


RUN cd /root/block-db && \
    cd third_party && \
    bash ../script/build_third_party.sh -i /usr

RUN rm -rf /root/.ssh
RUN ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa
RUN cat /root/.ssh/id_rsa.pub > /root/.ssh/authorized_keys

RUN echo 'Asia/Shanghai' > /etc/timezone

RUN rm /etc/security/limits.conf && \
    echo 'root    soft    nofile  50000 ' >> /etc/security/limits.conf && \
    echo 'root    hard    nofile  50000 ' >> /etc/security/limits.conf && \
    echo 'root    soft    core  unlimited ' >> /etc/security/limits.conf && \
    echo 'root    hard    core  unlimited ' >> /etc/security/limits.conf

