networks:
  bdb-network:
    attachable: true
    driver: overlay
    ipam:
      config:
        - gateway: 192.168.0.1
          subnet: 192.168.0.0/16
    name: bdb-network
services:
  bdb-client-az3:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 40G
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.3.100
    tty: true
  bdb-pnb-az3:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.3.101
    tty: true
  bdb-s1-az1-all:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.1.1
    tty: true
  bdb-s1-az2-all:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.2.1
    tty: true
  bdb-s1-az3-all:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.3.1
    tty: true
  bdb-s2-az1-all:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.1.2
    tty: true
  bdb-s2-az2-all:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.2.2
    tty: true
  bdb-s2-az3-all:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.3.2
    tty: true
  bdb-s3-az1-all:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.1.3
    tty: true
  bdb-s3-az2-all:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.2.3
    tty: true
  bdb-s3-az3-all:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.3.3
    tty: true
  bdb-s4-az1-all:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.1.4
    tty: true
  bdb-s4-az2-all:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.2.4
    tty: true
  bdb-s4-az3-all:
    build: ..
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10GB
        reservations:
          cpus: '0.25'
          memory: 1G
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.3.4
    tty: true
version: '3.8'
