networks:
  bdb-network:
    attachable: true
    driver: overlay
    ipam:
      config:
        - gateway: 192.168.0.1
          subnet: 192.168.0.0/16
    name: bdb-network
services:
  bdb-client-az3:
    build: ..
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.3.100
    tty: true
  bdb-s1-az1-all:
    build: ..
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.1.1
    tty: true
  bdb-s1-az2-all:
    build: ..
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.2.1
    tty: true
  bdb-s1-az3-all:
    build: ..
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    image: block-db
    networks:
      bdb-network:
        ipv4_address: 192.168.3.1
    tty: true
version: '3.8'
